# Generated by Django 5.0.1 on 2024-05-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelink',
            name='is_paid',
        ),
    ]
