# Generated by Django 5.0.1 on 2024-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_imagelink_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='is_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='watermarks/'),
        ),
    ]
