# Generated by Django 5.0.1 on 2024-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_imagelink_is_watermark_imagelink_watermark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='imagefile',
            field=models.ImageField(upload_to=''),
        ),
    ]
